version: 2.0

workflows:
  ios:
    name: iOS Build
    platform: ios
    dependencies:
      caches:
        - cocoapods
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
