version: 2.0

workflows:
  ios:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default  # Use the default CocoaPods version provided by Codemagic
    scripts:
      - name: Clean the project
        script: |
          flutter clean
      - name: Update Flutter
        script: |
          flutter upgrade
      - name: Regenerate iOS files
        script: |
          flutter create . --org com.taherml
      - name: Update Podfile if necessary
        script: |
          # Modify the Podfile to set the platform version and ensure workspace is set
          echo "platform :ios, '13.0'" > ios/Podfile
          echo "workspace 'Runner.xcworkspace'" >> ios/Podfile
          # Ensure dependencies are added (if necessary, depending on your project setup)
          # Add app_settings and any other dependencies
          echo "pod 'app_settings', '~> 4.0.0'" >> ios/Podfile
          # This will ensure that pod dependencies are properly included
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - aboayham250@gmail.com
