version: 2.0

workflows:
  ios:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default  # Use the default CocoaPods version provided by Codemagic
    scripts:
      - name: Clean the project
        script: |
          flutter clean
      - name: Update Flutter
        script: |
          flutter upgrade
      - name: Regenerate iOS files
        script: |
          flutter create . --org com.taherml
      - name: Update Podfile if necessary
        script: |
          # Modify the Podfile to set the platform version and ensure workspace is set
          echo "platform :ios, '13.0'" > ios/Podfile
          echo "use_frameworks!" >> ios/Podfile
          echo "target 'Runner' do" >> ios/Podfile
          echo "  use_flutter!" >> ios/Podfile
          echo "  pod 'app_settings', '~> 4.0.0'" >> ios/Podfile
          echo "end" >> ios/Podfile
          echo "post_install do |installer|" >> ios/Podfile
          echo "  installer.pods_project.targets.each do |target|" >> ios/Podfile
          echo "    flutter_additional_ios_build_settings(target)" >> ios/Podfile
          echo "  end" >> ios/Podfile
          echo "end" >> ios/Podfile
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - aboayham250@gmail.com
