version: 2.0

workflows:
  ios:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean the project
        script: |
          flutter clean
      - name: Update Flutter
        script: |
          flutter upgrade
      - name: Regenerate iOS files
        script: |
          flutter create . --org com.taherml
      - name: Clean iOS Pods
        script: |
          cd ios
          pod deintegrate
          # Ensure Podfile exists and set platform version
          if [ ! -f "Podfile" ]; then
            echo "platform :ios, '12.0'" > Podfile
            echo "workspace 'Runner.xcworkspace'" >> Podfile
            echo "use_frameworks!" >> Podfile
            echo "use_flutter!" >> Podfile
          fi
          pod install --repo-update
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - aboayham250@gmail.com
