version: 2.0

workflows:
  ios:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean the project
        script: |
          flutter clean
      - name: Update Flutter
        script: |
          flutter upgrade
      - name: Regenerate iOS files
        script: |
          flutter create . --org com.taherml
      - name: Clean iOS Pods
        script: |
          cd ios
          pod deintegrate
          pod repo update
          rm Podfile
          flutter precache
          flutter pub get
          flutter create .
      - name: Install specific CocoaPods version
        script: |
          gem cleanup
          brew uninstall cocoapods
          sudo gem uninstall cocoapods
          sudo gem install cocoapods -v 1.10.0 -n /usr/local/bin
          sudo gem install public_suffix -v 5.1.1
          sudo gem install cocoapods-user-defined-build-types -v 1.0.0
      - name: Update Podfile if necessary
        script: |
          echo "platform :ios, '13.0'" > ios/Podfile
          echo "use_frameworks!" >> ios/Podfile
          echo "target 'Runner' do" >> ios/Podfile
          echo "  use_flutter!" >> ios/Podfile
          echo "  pod 'app_settings', '~> 4.0.0'" >> ios/Podfile
          echo "end" >> ios/Podfile
          echo "post_install do |installer|" >> ios/Podfile
          echo "  installer.pods_project.targets.each do |target|" >> ios/Podfile
          echo "    flutter_additional_ios_build_settings(target)" >> ios/Podfile
          echo "  end" >> ios/Podfile
          echo "end" >> ios/Podfile
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - aboayham250@gmail.com
