version: 2.0

workflows:
  ios:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: latest  # Ensure CocoaPods is installed and up to date
    scripts:
      - name: Clean the project
        script: |
          flutter clean
      - name: Update Flutter
        script: |
          flutter upgrade
      - name: Regenerate iOS files
        script: |
          flutter create . --org com.taherml
      - name: Update Podfile if necessary
        script: |
          # Modify Podfile if specific changes are required (e.g., platform version)
          sed -i '' 's/platform :ios, \'9.0\'/platform :ios, \'10.0\'/' ios/Podfile
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - aboayham250@gmail.com
