name: gallery_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  

  firebase_core: ^3.7.0  
  firebase_auth: ^5.3.2   
  cloud_firestore: ^5.4.5 
  firebase_storage: ^12.3.5 
  firebase_messaging: ^15.1.6 
  image_picker: ^1.1.2
  image: ^4.3.0
  exif: ^3.3.0
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  flutter_image_compress: ^2.3.0
  logger: ^2.5.0
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  workmanager: ^0.5.2
  flutter_local_notifications: ^18.0.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  cloud_functions: ^5.2.0
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
