// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD55-OSJWLfrYT3n8wErEi78h_8kfilqNE',
    appId: '1:902876200409:web:e0fe7ce89b7beadcd42dc8',
    messagingSenderId: '902876200409',
    projectId: 'gallery-app-5d22d',
    authDomain: 'gallery-app-5d22d.firebaseapp.com',
    storageBucket: 'gallery-app-5d22d.firebasestorage.app',
    measurementId: 'G-7T9F89LYPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh98zVToPQNFTn50FydSpvPVIk53IcuaY',
    appId: '1:902876200409:android:fd8f25b1f36c3b9bd42dc8',
    messagingSenderId: '902876200409',
    projectId: 'gallery-app-5d22d',
    storageBucket: 'gallery-app-5d22d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_vMVvCWEa0sXWMdHDKRImhB5OPKuSgXI',
    appId: '1:902876200409:ios:f907f8d94d9baaacd42dc8',
    messagingSenderId: '902876200409',
    projectId: 'gallery-app-5d22d',
    storageBucket: 'gallery-app-5d22d.firebasestorage.app',
    iosBundleId: 'com.example.galleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_vMVvCWEa0sXWMdHDKRImhB5OPKuSgXI',
    appId: '1:902876200409:ios:f907f8d94d9baaacd42dc8',
    messagingSenderId: '902876200409',
    projectId: 'gallery-app-5d22d',
    storageBucket: 'gallery-app-5d22d.firebasestorage.app',
    iosBundleId: 'com.example.galleryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD55-OSJWLfrYT3n8wErEi78h_8kfilqNE',
    appId: '1:902876200409:web:ace2d6018f0695dfd42dc8',
    messagingSenderId: '902876200409',
    projectId: 'gallery-app-5d22d',
    authDomain: 'gallery-app-5d22d.firebaseapp.com',
    storageBucket: 'gallery-app-5d22d.firebasestorage.app',
    measurementId: 'G-VDBBSNM7MN',
  );
}
