platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  # Flutter Pod
  use_flutter!

  # Add your pods here
  # pod 'SomePod', '~> 1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
