platform :ios, '13.0'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Pods for Runner
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Add any additional CocoaPods you want here
  # For example, if you need Firebase Auth, add:
  # pod 'Firebase/Auth'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
